---
name: Pod-2-DocBook
version: 0.02_02
author:
  - 'Jozef Kutej <jkutej@cpan.org>'
abstract: Convert Pod data to DocBook SGML
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Digest::MD5: 0
  List::MoreUtils: 0
  Pod::ParseLink: 0
  Pod::Parser: 0
  Text::ParseWords: 0
  Text::Wrap: 0
build_requires:
  Test::More: 0
  XML::LibXML: 0
provides:
  Pod::2::DocBook:
    file: lib/Pod/2/DocBook.pm
    version: 0.02_02
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
